[WIP][hybris-boot] Android q split init
mer-hybris/hybris-boot pull request #174
Opened 2019-10-21 04:59 UTC by Thaodan

Starting with Android 10 init is split up in two[1][2][3]: second and late
stage init, with one for vendor and one for system init.

[1] https://android.googlesource.com/platform/system/core/+/31438489c0e263ca39f7ba77fe4e50334f2efab7
[2] https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r6/init/Android.bp#156
[3] https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r6/init/Android.mk#60

Depends on #173

2020-10-19 10:40 UTC, sledges commented on Android.mk
> +HYBRIS_INIT_TARGETS := init_second_stage init_system init_vendor
```init_system``` and ```init_vendor``` are created as fake packages and deem not to be needed for ```hybris-hal```.

2020-10-19 10:42 UTC, sledges requested changes
Thanks for your contrib!

2020-10-19 10:42 UTC, sledges commented on Android.mk
> +HYBRIS_INIT_TARGETS := init_second_stage init_system init_vendor
```init_system``` and ```init_vendor``` are created as fake packages and deem not to be needed for ```hybris-hal```.

2020-10-19 10:42 UTC, sledges commented on Android.mk
> +endif
Best to move this whole block above ```HYBRIS_COMMON_TARGETS := ...``` and add ```$(HYBRIS_INIT_TARGETS)``` to it.

2020-10-19 10:42 UTC, sledges commented on Android.mk
> +hybris-common: $(HYBRIS_COMMON_TARGETS) $(HYBRIS_INIT)
```hybris-common``` got orphaned during development and is no longer used (not part of ```hybris-hal``` target).

2020-10-19 10:46 UTC, sledges requested changes
There is a small word missing in the 2nd commit message: ... is greater **or** equal 10
I suggest the following commit message+description, to keep it short (and move ```[tag] foo``` to the bottom):

```
hybris-boot: Split up init for Android 10+

Starting with Android 10 init is split up in two[1][2][3]: second and late
stage init, with one for vendor and one for system init.

[1] https://android.googlesource.com/platform/system/core/+/31438489c0e263ca39f7ba77fe4e50334f2efab7
[2] https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r6/init/Android.bp#156
[3] https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r6/init/Android.mk#60

[hybris-boot] Split up init for Android 10+
```

2020-10-26 11:27 UTC, sledges requested changes
`[hybris-boot] Reuse mkbootimg` has been already merged, please rebase.

I would modify the main commit message: it's style (to match other commits of this repo) and content (because we don't split init in hybris-boot -- android 10 has done that not us, -- we just build one of its parts), also shortened commit message so it's not cut in github WebUI:

```
[hybris-boot] Build only init_second_stage for Android 10+

Starting with Android 10 init is split up into parts [1][2][3]: ramdisk, second,
and late stage init, with one for vendor and one for system init.

Some manufacturers choose to implement vendor and system init as fake
packages only.

[1] https://android.googlesource.com/platform/system/core/+/31438489c0e263ca39f7ba77fe4e50334f2efab7
[2] https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r6/init/Android.bp#156
[3] https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r6/init/Android.mk#60

Signed-off-by: Björn Bidar <bjorn.bidar@jolla.com>
```

2020-10-26 11:53 UTC, Thaodan commented
>I would modify the main commit message: it's style (to match other commits of this repo) 

Thats exactly what I did as some commits use the [tag] message style vs. some that use tag: message and then later [tag] message. But I can change it again to [tag] message. It is often confusing to find the proper style when there is no consistency.


>[...] because we don't split init in hybris-boot -- android 10 has done that not us -- [...]

Thats what i wanted to say but your is more accurate I will changes this.

2020-10-26 11:58 UTC, sledges commented
> > I would modify the main commit message: it's style (to match other commits of this repo)
> 
> Thats exactly what I did as some commits use the [tag] message style vs. some that use tag: message and then later [tag] message. But I can change it again to [tag] message. It is often confusing to find the proper style when there is no consistency.

Thanks, after quick looking through history, this hybris-boot repo has "tag: message" only in one commit in the last 3 years (and that was a reviewer's, probably me, fault for accepting too hastily:). Others are "[tag] message".

2020-10-30 08:18 UTC, sledges approved these changes

2020-10-30 08:19 UTC, merged